name: Deploy to Dokku Prod

on:
  push:
    branches:
      - master

jobs:
  check:
    uses: wondersell/rembg/.github/workflows/build-and-test.yml@master

  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@moscow.wondersellcloud.ru:22/rembg'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
